### ISSUE TITLE
What's up with the TGen stuff?

### ISSUE THREAD

**Issue by prescientmoon** [osa1/MANTI#1]
I've looked over your code (for educational purpouses) and I'm confused as to why the instantiation/generalization stuff is necessary

**Comment by osa1** [comment]
`TVGen`s are generalized variables. When you parse a rule like

```prolog
member(A, [A|_]).
member(A, [_|Rest]) :- member(A, Rest).
```

(from examples/list.pl)

you replace the argument variables (`A` and `Rest`) with `TVGen`s in `Types.generalize`. Then, when you see an application of a rule (like the RHS use of `member` above), you find the definition of the predicate, and "instantiate" (`Types.instantiate`) it, which basically creates fresh unification variables for generalized variables (`TVGens`).

Effectively what this does is it creates new unification variables of each application of a rule so you can use a single unification map (`Unify.Substs`) for all variables in scope.

Without this, if you have two matching rules for a predicate, like `X(Y, Z)`, where both rules use the same variable names, you would need to somehow distinguish these variables with same names, so that unifying one with a term during search won't automatically unify the other.

(There may be other reasons as well, but it's been a while since I worked on this project, so I don't remember all the details)

Is this helpful? Let me know if you have more questions.

**Comment by prescientmoon** [comment]
Thanks, that makes a lot of sense!
